version: '3.9'
services:
  app:
    build:
      context: app/
      dockerfile: Dockerfile
    entrypoint: /app/entrypoint.sh
    ports:
      - "5000:5000"
    depends_on:
      app_db: 
        condition: service_healthy


  api:
    build:
      context: api/
      dockerfile: Dockerfile
    hostname: api
    entrypoint: /api/entrypoint.sh
    ports:
      - "5001:5001"
    depends_on:
      - api_db

  scraper:
    build:
      context: scraper/
      dockerfile: Dockerfile

  api_db:
    image: postgres:14
    hostname: api_db
    environment:
      - POSTGRES_DB=assets_db
      - POSTGRES_USERS=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  app_db:
    image: postgres:14
    hostname: app_db
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USERS=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always