"""empty message

Revision ID: 49d90c1f2f86
Revises: ba20770d37ab
Create Date: 2022-05-24 12:00:27.654138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d90c1f2f86'
down_revision = 'ba20770d37ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('AssetsUsers_username_key', 'AssetsUsers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('AssetsUsers_username_key', 'AssetsUsers', ['username'])
    # ### end Alembic commands ###
