"""empty message

Revision ID: ba20770d37ab
Revises: 7f0a679bdbbc
Create Date: 2022-05-24 11:40:20.704488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba20770d37ab'
down_revision = '7f0a679bdbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Assets',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('AssetsPriceHistory',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['Assets._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('AssetsUsers',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['asset_name'], ['Assets.name'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('assets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('abbreviation', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('_id', name='assets_pkey')
    )
    op.drop_table('AssetsUsers')
    op.drop_table('AssetsPriceHistory')
    op.drop_table('Assets')
    # ### end Alembic commands ###
